USE [BIA]
GO
/****** Object:  StoredProcedure [dbo].[usp_ETL_Load_MART_TRANS_DAILY_GECADE]    Script Date: 2018-07-02 08:10:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[usp_ETL_Load_MART_TRANS_DAILY_GECADE]
AS

DECLARE @SP date, @EP date, @SPN int, @EPN int;
DECLARE @DateFrom date;
DECLARE @DateTo date;

/****FOR DAILY JOBS****/
set @DateFrom = DATEADD(month,-1,DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0))
if DATEPART(day,getdate()) > 15 begin set @DateFrom = DATEADD(month,0,DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0)) end	
set @DateTo = cast(getdate() as Date)

/****FOR ADHOC CALCULATIONS****/
--SET @DateFrom = '2016-01-01'
--SET @DateTo = '2018-06-28'


DROP TABLE IF EXISTS #MART_DAILY_MERCH_TRANS_GECADE_TMP;

SELECT
   CAST(TE.TRANS_CREATE_DATE AS DATE) AS CREATE_DATE
  ,CO.COUNTRY_CODE
  ,PMF.M_FIRM_ID as ACCOUNT_ID
  ,PMF.POS_MERCHANT_ID AS MERCH_ID
  ,GH.MERCHANT_HOST AS MERCH_HOST
  ,GW.SERVICE_PROVIDER
  ,PMF.M_MCC
  ,M_TYPE AS ACCOUNT_TYPE
  ,TE.TRANS_CURRENCY
  --MEASURES:
  ,COUNT(TE.TRANS_ID) TPT_CREA
  ,SUM(TE.TRANS_AMOUNT) AS TPV_CREA

  --,SUM(CASE WHEN TE.TRANS_ID_DATE_SENT IS NOT NULL THEN 1 END) TPT_SENT
  --,SUM(CASE WHEN TE.TRANS_ID_DATE_SENT IS NOT NULL THEN TE.TRANS_AMOUNT END) TPV_SENT

  ,SUM(CASE WHEN TE.TRANS_STATUS = 99 THEN 1 END) TPT_SUCC
  ,SUM(CASE WHEN TE.TRANS_STATUS = 99 THEN TE.TPV END) TPV_SUCC

  ,COUNT(case when GW.TRANS_GW_NAME_TYPE = 'Payment Card' then TE.TRANS_ID end) TPT_CARD_CREA
  ,SUM(case when GW.TRANS_GW_NAME_TYPE = 'Payment Card' then TE.TRANS_AMOUNT end) TPV_CARD_CREA
  ,SUM(CASE WHEN TE.TRANS_STATUS = 99 AND GW.TRANS_GW_NAME_TYPE = 'Payment Card' THEN TE.TPV END) TPV_CARD_SUCC
  ,COUNT(CASE WHEN TE.TRANS_STATUS = 99 AND GW.TRANS_GW_NAME_TYPE = 'Payment Card' THEN TRANS_ID END) TPT_CARD_SUCC

  ,COUNT(case when GW.TRANS_GW_NAME_TYPE = 'Installments' then TE.TRANS_ID end) TPT_INSTALL_CREA
  ,SUM(case when GW.TRANS_GW_NAME_TYPE = 'Installments' then TE.TRANS_AMOUNT end) TPV_INSTALL_CREA
  ,SUM(CASE WHEN TE.TRANS_STATUS = 99 AND GW.TRANS_GW_NAME_TYPE = 'Installments' THEN TE.TPV END) TPV_INSTALL_SUCC
  ,COUNT(CASE WHEN TE.TRANS_STATUS = 99 AND GW.TRANS_GW_NAME_TYPE = 'Installments' THEN TRANS_ID END) TPT_INSTALL_SUCC

  ,COUNT(case when GW.TRANS_GW_NAME_TYPE = 'Test payment' then TE.TRANS_ID end) TPT_TEST_CREA
  ,SUM(case when GW.TRANS_GW_NAME_TYPE = 'Test payment' then TE.TRANS_AMOUNT end) TPV_TEST_CREA
  ,SUM(CASE WHEN TE.TRANS_STATUS = 99 AND GW.TRANS_GW_NAME_TYPE = 'Test payment' THEN TE.TPV END) TPV_TEST_SUCC
  ,COUNT(CASE WHEN TE.TRANS_STATUS = 99 AND GW.TRANS_GW_NAME_TYPE = 'Test payment' THEN TRANS_ID END) TPT_TEST_SUCC

  ,SUM(TPT) TPT_BILL
  ,SUM(TPV) TPV_BILL
  ,SUM(TPV_USD) TPV_BILL_USD
  ,SUM(COMMISSION) AS COMM
  ,SUM(COMMISSION_USD) AS COMM_USD
  ,SUM(ISNULL(ACT_FEE,0)) AS ACT_FEE
  ,SUM(ISNULL(ACT_FEE_USD,0)) AS ACT_FEE_USD
  ,SUM(COPS) COPS
  ,SUM(COPS_USD) COPS_USD
  ,SUM(COMMISSION)+SUM(ISNULL(ACT_FEE,0)) AS REV
  ,SUM(COMMISSION_USD)+SUM(ISNULL(ACT_FEE_USD,0)) AS REV_USD

INTO #MART_DAILY_MERCH_TRANS_GECADE_TMP

FROM
[DWH].[dbo].[FACT_TRANSACTIONS_EXT] TE
	LEFT JOIN [DWH].[dbo].[DIM_POS_MER_FIRM] PMF ON TE.TRANS_ID_VER_POS_MER_FIRM = PMF.ID_VER
	LEFT JOIN [DWH].[dbo].[DIM_TRANS_GW_NAME] GW ON TE.TRANS_ID_TRANS_GW_NAME = GW.ID_TRANS_GW_NAME
	LEFT JOIN [DWH].[dbo].[DIM_PRODUCT_BASE] P ON TE.TRANS_ID_PRODUCT = P.ID_PRODUCT
	LEFT JOIN [DWH].[dbo].[DIM_CARD_PAYMENT] CP ON TE.TRANS_ID_PC = CP.ID_CARD_PAYMENT
	LEFT JOIN [DWH].[dbo].[DIM_COUNTRY] CO ON TE.TRANS_ID_COUNTRY = CO.ID_COUNTRY
	LEFT JOIN [DWH].[dbo].[DICT_AUTOBOARDING_FLAG] AF ON AF.M_FIRM_ID = PMF.M_FIRM_ID AND PMF.FIRM_BA_ORIGIN = AF.FIRM_BA_ORIGIN

	LEFT JOIN (
	   SELECT TMP.FIRM_BA_ORIGIN, TMP.POS_MERCHANT_ID, TMP.MERCHANT_HOST AS MERCHANT_HOST_OLD
	   ,SUBSTRING(TMP.MERCHANT_HOST,1,CASE WHEN CHARINDEX(' ',TMP.MERCHANT_HOST)=0 THEN LEN(TMP.MERCHANT_HOST) ELSE CHARINDEX(' ',TMP.MERCHANT_HOST) END) MERCHANT_HOST
	   FROM [DWH].[dbo].[DIM_POS_MER_FIRM] TMP
	   WHERE 1=1
		AND IS_CURRENT = 1
	     AND FIRM_BA_ORIGIN IN ('RU','TR','RO')
		  ) gh ON gh.FIRM_BA_ORIGIN = pmf.FIRM_BA_ORIGIN
		  AND gh.POS_MERCHANT_ID	 = pmf.POS_MERCHANT_ID

WHERE 1=1
	AND TE.TRANS_CREATE_DATE >= @DateFrom
	AND TE.TRANS_CREATE_DATE < @DateTo
	AND PMF.EXCLUDED = 0
	AND CO.COUNTRY_CODE IN ('RU','RO','TR')
GROUP BY

   CAST(TE.TRANS_CREATE_DATE AS DATE)
  ,CO.COUNTRY_CODE
  ,PMF.M_FIRM_ID 
  ,PMF.POS_MERCHANT_ID 
  ,GH.MERCHANT_HOST 
  ,GW.SERVICE_PROVIDER
  ,PMF.M_MCC
  ,PMF.M_TYPE
  ,TE.TRANS_CURRENCY
;

/******************************
REPLACE OR INSERT PARTITIONS
*******************************/


SELECT @SPN=$PARTITION.[pf_Month_Date](@DateFrom),@EPN=$PARTITION.[pf_Month_Date](@DateTo) 
TRUNCATE TABLE dbo.MART_DAILY_MERCH_TRANS_GECADE
WITH (PARTITIONS (@SPN TO @EPN));

INSERT INTO [dbo].MART_DAILY_MERCH_TRANS_GECADE WITH ( TABLOCKX )
SELECT * FROM #MART_DAILY_MERCH_TRANS_GECADE_TMP;


/*REMOVE TMP TABLES*/
DROP TABLE IF EXISTS #MART_DAILY_MERCH_TRANS_GECADE_TMP;



/*MERCH ID AGGREGATIONS*/

DROP TABLE IF EXISTS [dbo].[MART_MONTHLY_MERCH_ID_TRANS_GECAD];

SELECT
 MT.MERCH_ID
,MT.COUNTRY_CODE
,DATEADD(month, DATEDIFF(month, 0, CREATE_DATE), 0) [MONTH]

,SUM(MT.TPT_CREA) AS TPT_CREA
,SUM(mt.TPT_CARD_CREA) AS TPT_CARD_CREA
,SUM(MT.TPT_SUCC) AS TPT_SUCC
,SUM(mt.TPT_CARD_SUCC) AS TPT_CARD_SUCC

,SUM(MT.TPV_CREA) AS TPV_CREA
,SUM(mt.TPV_CARD_CREA) AS TPV_CARD_CREA
,SUM(MT.TPV_SUCC) AS TPV_SUCC
,SUM(mt.TPV_CARD_SUCC) AS TPV_CARD_SUCC

,MAX(CASE WHEN COALESCE(TPT_SUCC,0) > 0 THEN CREATE_DATE END) LST_TPT_SUCC_IN_MTH
,MIN(CASE WHEN COALESCE(TPT_SUCC,0) > 0 THEN CREATE_DATE END) FST_TPT_SUCC_IN_MTH

INTO [dbo].[MART_MONTHLY_MERCH_ID_TRANS_GECAD]

FROM [dbo].MART_DAILY_MERCH_TRANS_GECADE MT
WHERE 1=1
--AND MERCH_HOST IS NOT NULL

GROUP BY
 MT.MERCH_ID
,MT.MERCH_HOST
,MT.COUNTRY_CODE
,DATEADD(month, DATEDIFF(month, 0, MT.CREATE_DATE), 0)
;


DROP TABLE IF EXISTS [dbo].[MART_DIM_MERCH_ID_TRANS_GECAD];

SELECT
 MERCH_ID
,COUNTRY_CODE

,SUM(CASE WHEN MONTH BETWEEN '2018-01-01' AND '2018-12-01' THEN TPT_SUCC ELSE 0 END) TPT_SUCC_2018
,SUM(CASE WHEN MONTH BETWEEN '2017-01-01' AND '2017-12-01' THEN TPT_SUCC ELSE 0 END) TPT_SUCC_2017
,SUM(CASE WHEN MONTH BETWEEN '2016-01-01' AND '2016-12-01' THEN TPT_SUCC ELSE 0 END) TPT_SUCC_2016
,SUM(CASE WHEN MONTH BETWEEN '2015-01-01' AND '2015-12-01' THEN TPT_SUCC ELSE 0 END) TPT_SUCC_2015

,SUM(CASE WHEN MONTH BETWEEN '2018-01-01' AND '2018-12-01' THEN TPV_SUCC ELSE 0 END) TPV_SUCC_2018
,SUM(CASE WHEN MONTH BETWEEN '2017-01-01' AND '2017-12-01' THEN TPV_SUCC ELSE 0 END) TPV_SUCC_2017
,SUM(CASE WHEN MONTH BETWEEN '2016-01-01' AND '2016-12-01' THEN TPV_SUCC ELSE 0 END) TPV_SUCC_2016
,SUM(CASE WHEN MONTH BETWEEN '2015-01-01' AND '2015-12-01' THEN TPV_SUCC ELSE 0 END) TPV_SUCC_2015

,COUNT(DISTINCT CASE WHEN MONTH BETWEEN '2018-01-01' AND '2018-12-01' AND TPT_SUCC > 0 THEN MONTH END) MTH_ACTIVE_TPT_2018
,COUNT(DISTINCT CASE WHEN MONTH BETWEEN '2017-01-01' AND '2017-12-01' AND TPT_SUCC > 0 THEN MONTH END) MTH_ACTIVE_TPT_2017
,COUNT(DISTINCT CASE WHEN MONTH BETWEEN '2016-01-01' AND '2016-12-01' AND TPT_SUCC > 0 THEN MONTH END) MTH_ACTIVE_TPT_2016
,COUNT(DISTINCT CASE WHEN MONTH BETWEEN '2015-01-01' AND '2015-12-01' AND TPT_SUCC > 0 THEN MONTH END) MTH_ACTIVE_TPT_2015

,MAX(LST_TPT_SUCC_IN_MTH) LST_TPT_SUCC
,MIN(FST_TPT_SUCC_IN_MTH) FST_TPT_SUCC

INTO [dbo].[MART_DIM_MERCH_ID_TRANS_GECAD]

FROM [dbo].[MART_MONTHLY_MERCH_ID_TRANS_GECAD]

GROUP BY
 MERCH_ID
,COUNTRY_CODE
;